### ISSUE TITLE
Anyway to use this without mega hack?

### ISSUE THREAD

**Issue by ICantReadYourMind** [theyareonit/GDInputLag#1]
Title

**Comment by theyareonit** [comment]
i'm pretty sure it works even without mega hack (though i havent tested it), u just have to put MinHook.x86.dll in your gd folder and load the mod with dll loader whenever you start the game

**Comment by theyareonit** [comment]
it works with any dll loader, as long as u have MinHook.x86.dll in your GD folder. i've updated the readme to make that more clear.
